server:
  port: 10001

spring:
  application:
    name: api-gateway

zuul:
  routes:
    api-test:
      path: /api-test/**
      serviceId: hello-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: zuul
      client-secret: zuul-secret
      access-token-uri: http://localhost:10002/oauth/token
      user-authorization-uri: http://localhost:10002/oauth/authorize
    resource:
      user-info-uri:  http://localhost:10002/user
      prefer-token-info: false
